title: NeuroCognitive Imaging Lab
subtitle: at Dalhousie University
description: Directed by Dr. Aaron J Newman
header: images/header.jpeg
footer: images/header.jpeg
links:
  email: ncil@dal.ca
  orcid: 0000-0001-5290-8342
  google-scholar: CZySdSoAAAAJ
  github: NeuroCognitiveImagingLab
  twitter: NCILab
  instagram: ncilab
  youtube: NeuroCognitiveImagingLab
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: ncil@dal.ca
github: NeuroCognitiveImagingLab
twitter: NCILab
instagram: NCILab
youtube: NeuroCognitiveImagingLab
