- id: doi:10.1023/A:1010499119393
  title: "An Event-Related fMRI Study of Syntactic and Semantic Violations"

- id: 10.1016/j.mex.2023.102019
  image: images/two_for_one.png

- id: 10.1145/3544548.3580943
  image: images/are_you_human.png 

-   